name: Enumerate themes into a database file

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip

      - name: execute py script # run main.py
        id: getfiles
        run: python main.py "Themes" ".wptp"
          
      - name: Overwrite file
        uses: "DamianReeves/write-file-action@master"
        with:
          path: store.wpdb
          write-mode: overwrite
          contents: | 
            ${{ steps.getfiles.outputs.paths }}
            
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: "Themes database"
