name: Enumerate themes into a database file

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch action
        id: pl
        uses: Rishabh510/Path-lister-action@master
        with:
          path: ".github/Themes/"
          type: ".wptp"
          
      - name: Overwrite file
        uses: "DamianReeves/write-file-action@master"
        with:
          path: store.wpdb
          write-mode: overwrite
          contents: ${{ steps.pl.outputs.paths }}
            
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
