# Workflow name and description
name: EnumThemes
run-name: Enumerate themes into a database file 'store.wpdb'

on:
  # Trigger the workflow on push to 'main' branch or manually via workflow_dispatch
  push:
    branches: [ main ]    # Trigger on push to the main branch
    paths: Themes/**      # Trigger only if files in the 'Themes' directory change
  workflow_dispatch:        # Allows manual triggering from GitHub Actions UI

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner for this job

    steps:
      # Step 1: Checkout repository content
      - name: Checkout repo
        uses: actions/checkout@v3
        # This action checks out the repository so that the workflow can access the files

      # Step 2: Set up Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Install Python 3.10

      # Step 3: Install required Python packages
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to the latest version
          pip install GitPython               # Install GitPython for Git operations

      # Step 4: Run the Python script to enumerate themes into a database file
      - name: Execute Python script
        id: getfiles
        run: python main.py Themes store.wpdb
        # Arguments:
        #   'Themes' is the directory containing theme files
        #   'store.wpdb' is the output database file to store the enumerated themes
