name: Enumerate Themes
on: [push]
permissions:
  actions: write
  checks: write
  contents: write
  pages: write
  pull-requests: write
  repository-projects: write

run-name: Enumerating themes to be public to all
  
jobs:
  list:
    name: Path lister
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
          
      - uses: actions/checkout@v1
          
      - name: Execute python script
        run: |
          python enumthemes.py

      - name: Output results
        run: |
          echo ${{ steps.pl.outputs.paths }}
