name: Enumerate Themes
on: [push]
permissions:
  actions: write
  checks: write
  contents: write
  pages: write
  pull-requests: write
  repository-projects: write

run-name: Enumerating themes to be public to all
  
jobs:
  find-jobs:
    name: Find Jobs
    container: debian:buster-slim
    outputs:
      folders: ${{ steps.jobs.outputs.folders }}
    steps:
      - uses: actions/checkout@v1

      - id: jobs
        uses: philips-labs/list-folders-action@v1
        with:
          path: ./Themes
