name: Enumerate Themes
on: [push]
permissions:
  actions: write
  checks: write
  contents: write
  pages: write
  pull-requests: write
  repository-projects: write
run-name: Enumerating themes to be public to all

jobs:
      -name: create-json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "themes_db.json"
          json: 'X'
