name: Enumerate Themes
on: [push]
permissions:
  actions: write
  checks: write
  contents: write
  pages: write
  pull-requests: write
  repository-projects: write
run-name: Enumerating themes to be public to all

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.14.6'
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "devdatatools-firebase-adminsdk.json"
          json: ${{ secrets.CREDENTIALS_JSON }}
          dir: "./Themes"
