name: Enumerate Themes
on: [push]

jobs:
  list:
    name: Path lister
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
          
      - uses: actions/checkout@v1
      
      - name: Fetch action
        id: pl
        uses: Rishabh510/Path-lister-action@master
        with:
          path: "Themes"
          type: ".wptp"
          
      - name: Writes File Action
        uses: BoundfoxStudios/action-write-file@v1
        with:
         path: ~/store.wpdb
         contents: ${{ steps.pl.outputs.paths }}
         write-mode: overwrite
    
      - name: Output results
        run: |
          echo ${{ steps.pl.outputs.paths }}
