name: Path lister example
on: [push]
jobs:
  list:
    name: Path lister
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - uses: actions/checkout@v1

      - name: Fetch action
        id: pl
        uses: Rishabh510/Path-lister-action@master
        with:
          path: "Themes"
          type: ".wptp"

      - name: Output results
        run: |
          for i in ${{ steps.pl.outputs.paths }}; do
          echo $i
          done
          
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
         name: my-artifact
         path: my_file.txt
